### ISSUE TITLE
Broken Skeleton Missing Lang

### ISSUE THREAD

**Issue by burghenby** [Sh1nyLabs/Bones-update#3]
Hello! This is just a small thing, but I noticed that Broken Skeletons are missing their names in the lang file. When hovered over, we just see "entity.bonesupdate.broken_skeleton" instead of "Broken Skeleton."
![2024-09-20_18 06 45](https://github.com/user-attachments/assets/d2806039-7fcb-4a0a-91c8-9e2dbdc20882)

I tried to fix this with a custom resource pack but it doesn't seem to be working so I don't know if a resource pack can add to something that didn't exist previously. 🤷 

EDIT: Turns out the resource pack I made just to fix the lang wasn't being recognized by my game, but once I put the fixed lang in an already-established resource pack the game picked it up.
![2024-09-20_18 27 11](https://github.com/user-attachments/assets/95b20dc9-b952-4355-a15d-696853b90fce)

**Comment by Sh1nyLabs** [comment]
Hello burghenby, 

Thanks for reporting this  missing lang. It has been integrated to version 1.20.1 of the Bones Update mod (see version 1.2.0-1).
